### ISSUE TITLE
Pro version of Font Awesome needed?

### ISSUE THREAD

**Issue by ThomasEg** [automatica-core/automatica#16]
**Describe the bug**
When trying to build the sources as described in ReadMe for building the frontend(`Automatica.WebNew`) i get:
```npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-solid-svg-icons - Not found
npm ERR! 404
npm ERR! 404  '@fortawesome/pro-solid-svg-icons@5.7.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'Automatica.WebNew'
```

**Expected behavior**
I expect the install instructions in ReadMe works without any prerequesites unless otherwise specified. I bet you have a pro subscription and configured NPM to use that subscription.

**To Reproduce**
Follow the instructions in ReadMe on a "blank machine"(without any config set for the pro-subscription of fontawesome)

**automatica.core version**
Master-branch as of 17-08-2019

**Desktop (please complete the following information):**
 - OS: Windows 10
 - NPM: 6.10.1

**Comment by p3root** [comment]
Hey Thomas!

I guess I should remove fortawesome/pro, as the have no way to distribute the pro fonts in a opensource project.  I'm going to remove it from the develop branch for now. Some icons will not work then, but you can go forward to try it.

**Comment by p3root** [comment]
You can checkout the develop branch now. I have removed fortawesome/pro with commit a8e5794bca506868019ca0e66416884884e3039d

**Comment by ThomasEg** [comment]
Thanks! I saw that you actually just had the pro as an add-on, so i tried removing it myself and it worked fine...

however, i like the idea of people being able to easily add the pro-packages and switch the imports in app.component.ts (as you kinda already did, just reversed)

What about docker?
https://github.com/automatica-core/automatica/blob/a8e5794bca506868019ca0e66416884884e3039d/docker/automatica/Dockerfile#L24-L25

**Comment by p3root** [comment]
I changed the dockerfile locally but couldn't test it cause my docker did not work. Therefore I did not commit the change right now.

**Comment by p3root** [comment]
It should work also with the npm commands also.

**Comment by p3root** [comment]
I removed the entries from the dockerfile!
