### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by ThomasEg** [automatica-core/automatica#29]
**Describe the bug**
On the website https://www.automaticacore.com/ there is a link to https://demo.automaticacore.com/. It does not work.

**Comment by p3root** [comment]
Hey @ThomasEg !

Thanks for the information, I know it is down at the moment. I will fix this in the next couple days.

Cheers

**Comment by p3root** [comment]
Hey Thomas!

I have created a new demo. The current link is: 
https://automatica-test.azurewebsites.net/

Login with user: sa and password: sa

Sorry for being so late - but the current situation is not easy :/

Have fun :) And let me know what you think about it - i have redesigned a lot in the web interface.

cheers
