### ISSUE TITLE
How to Change Language to English?

### ISSUE THREAD

**Issue by zhouji0212** [automatica-core/automatica#58]
**Describe the bug**

**Expected behavior**

**To Reproduce**

**automatica.core version**
Tell me which version of the system do you use.

**plugin version**
If the bug depends on a plugin - tell me know this version.

**system**
On which system does automatica.core run. Eg Raspberry Pi 3+

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by p3root** [comment]
Could you provide a screenshot? English is indeed as default.

**Comment by zhouji0212** [comment]
is the project have forum or discord channel? i can post the picture

**Comment by p3root** [comment]
You can post it here. We have no discord or forum

**Comment by zhouji0212** [comment]
![image](https://user-images.githubusercontent.com/4176951/203781732-383bd47d-c149-4b3f-9654-aa797687f233.png)
the language like this not full english

**Comment by p3root** [comment]
Yeah, thats because the categories and areas in this demo were created in german.

**Comment by zhouji0212** [comment]
how can i change categories and areas into english?

**Comment by p3root** [comment]
depends on the locale you have set in your system! Default is always english!
