### ISSUE TITLE
The HomeKit Driver Demo Can't Add To Apple

### ISSUE THREAD

**Issue by zhouji0212** [automatica-core/automatica#61]
![image](https://user-images.githubusercontent.com/4176951/203784314-5972d4db-035b-48af-bef9-6f1a6ffa9a05.png)

i use my ipad add the homekit demo ,but can't add any accessory,it sho can't add accessory ipad show Homekit accessory out of compliance error

**Comment by p3root** [comment]
What kind of error do you see on your ipad?

I have tested it. Seems that the implementation is a little bit out of date.

**Comment by zhouji0212** [comment]
it cant run in windows😱

**Comment by p3root** [comment]
@zhouji0212 updated some code in the homekit driver. works on my side now. check the develop branch
